import React, { useRef } from "react";
import Menu from "../../components/Menu";
import Header from "../../components/Header";
import Footer from "../../components/Footer";

import styles from "./adminLayout.module.sass";
import useClickNotOnElement from "../../hooks/useClickNotOnElement";

export const AdminLayout = () => {
    const menu = useRef();
    const [showElement, setShowElement] = useClickNotOnElement(menu);
    return (
        <div className={styles.body}>
            <Menu
                showMenu={showElement}
                setShowMenu={setShowElement}
                ref={menu}
            />
            <div className={styles.wrapper}>
                <Header setShowMenu={setShowElement} />
                <main className={styles.content}>
                    lORE RWEFO JWOFN WEONFO WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ
                    OIERJGOIERPIUPJ PERWP FERPNG EWRNJG JNWER G[JWERGN WERNGW
                    ENR[O NWERO[ NW[GNE IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI
                    WNRVO[WRTG WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE
                    VMWOTJVN OWMV lORE RWEFO JWOFN WEONFO
                    WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ OIERJGOIERPIUPJ PERWP FERPNG
                    EWRNJG JNWER G[JWERGN WERNGW ENR[O NWERO[ NW[GNE
                    IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI WNRVO[WRTG
                    WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE VMWOTJVN
                    OWMV lORE RWEFO JWOFN WEONFO WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ
                    OIERJGOIERPIUPJ PERWP FERPNG EWRNJG JNWER G[JWERGN WERNGW
                    ENR[O NWERO[ NW[GNE IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI
                    WNRVO[WRTG WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE
                    VMWOTJVN OWMV lORE RWEFO JWOFN WEONFO
                    WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ OIERJGOIERPIUPJ PERWP FERPNG
                    EWRNJG JNWER G[JWERGN WERNGW ENR[O NWERO[ NW[GNE
                    IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI WNRVO[WRTG
                    WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE VMWOTJVN
                    OWMV lORE RWEFO JWOFN WEONFO WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ
                    OIERJGOIERPIUPJ PERWP FERPNG EWRNJG JNWER G[JWERGN WERNGW
                    ENR[O NWERO[ NW[GNE IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI
                    WNRVO[WRTG WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE
                    VMWOTJVN OWMV lORE RWEFO JWOFN WEONFO
                    WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ OIERJGOIERPIUPJ PERWP FERPNG
                    EWRNJG JNWER G[JWERGN WERNGW ENR[O NWERO[ NW[GNE
                    IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI WNRVO[WRTG
                    WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE VMWOTJVN
                    OWMV lORE RWEFO JWOFN WEONFO WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ
                    OIERJGOIERPIUPJ PERWP FERPNG EWRNJG JNWER G[JWERGN WERNGW
                    ENR[O NWERO[ NW[GNE IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI
                    WNRVO[WRTG WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE
                    VMWOTJVN OWMV lORE RWEFO JWOFN WEONFO
                    WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ OIERJGOIERPIUPJ PERWP FERPNG
                    EWRNJG JNWER G[JWERGN WERNGW ENR[O NWERO[ NW[GNE
                    IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI WNRVO[WRTG
                    WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE VMWOTJVN
                    OWMV lORE RWEFO JWOFN WEONFO WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ
                    OIERJGOIERPIUPJ PERWP FERPNG EWRNJG JNWER G[JWERGN WERNGW
                    ENR[O NWERO[ NW[GNE IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI
                    WNRVO[WRTG WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE
                    VMWOTJVN OWMV lORE RWEFO JWOFN WEONFO
                    WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ OIERJGOIERPIUPJ PERWP FERPNG
                    EWRNJG JNWER G[JWERGN WERNGW ENR[O NWERO[ NW[GNE
                    IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI WNRVO[WRTG
                    WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE VMWOTJVN
                    OWMV lORE RWEFO JWOFN WEONFO WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ
                    OIERJGOIERPIUPJ PERWP FERPNG EWRNJG JNWER G[JWERGN WERNGW
                    ENR[O NWERO[ NW[GNE IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI
                    WNRVO[WRTG WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE
                    VMWOTJVN OWMV lORE RWEFO JWOFN WEONFO
                    WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ OIERJGOIERPIUPJ PERWP FERPNG
                    EWRNJG JNWER G[JWERGN WERNGW ENR[O NWERO[ NW[GNE
                    IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI WNRVO[WRTG
                    WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE VMWOTJVN
                    OWMV lORE RWEFO JWOFN WEONFO WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ
                    OIERJGOIERPIUPJ PERWP FERPNG EWRNJG JNWER G[JWERGN WERNGW
                    ENR[O NWERO[ NW[GNE IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI
                    WNRVO[WRTG WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE
                    VMWOTJVN OWMV lORE RWEFO JWOFN WEONFO
                    WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ OIERJGOIERPIUPJ PERWP FERPNG
                    EWRNJG JNWER G[JWERGN WERNGW ENR[O NWERO[ NW[GNE
                    IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI WNRVO[WRTG
                    WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE VMWOTJVN
                    OWMV lORE RWEFO JWOFN WEONFO WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ
                    OIERJGOIERPIUPJ PERWP FERPNG EWRNJG JNWER G[JWERGN WERNGW
                    ENR[O NWERO[ NW[GNE IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI
                    WNRVO[WRTG WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE
                    VMWOTJVN OWMV lORE RWEFO JWOFN WEONFO
                    WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ OIERJGOIERPIUPJ PERWP FERPNG
                    EWRNJG JNWER G[JWERGN WERNGW ENR[O NWERO[ NW[GNE
                    IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI WNRVO[WRTG
                    WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE VMWOTJVN
                    OWMV lORE RWEFO JWOFN WEONFO WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ
                    OIERJGOIERPIUPJ PERWP FERPNG EWRNJG JNWER G[JWERGN WERNGW
                    ENR[O NWERO[ NW[GNE IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI
                    WNRVO[WRTG WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE
                    VMWOTJVN OWMV lORE RWEFO JWOFN WEONFO
                    WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ OIERJGOIERPIUPJ PERWP FERPNG
                    EWRNJG JNWER G[JWERGN WERNGW ENR[O NWERO[ NW[GNE
                    IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI WNRVO[WRTG
                    WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE VMWOTJVN
                    OWMV lORE RWEFO JWOFN WEONFO WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ
                    OIERJGOIERPIUPJ PERWP FERPNG EWRNJG JNWER G[JWERGN WERNGW
                    ENR[O NWERO[ NW[GNE IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI
                    WNRVO[WRTG WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE
                    VMWOTJVN OWMV lORE RWEFO JWOFN WEONFO
                    WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ OIERJGOIERPIUPJ PERWP FERPNG
                    EWRNJG JNWER G[JWERGN WERNGW ENR[O NWERO[ NW[GNE
                    IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI WNRVO[WRTG
                    WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE VMWOTJVN
                    OWMV lORE RWEFO JWOFN WEONFO WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ
                    OIERJGOIERPIUPJ PERWP FERPNG EWRNJG JNWER G[JWERGN WERNGW
                    ENR[O NWERO[ NW[GNE IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI
                    WNRVO[WRTG WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE
                    VMWOTJVN OWMV lORE RWEFO JWOFN WEONFO
                    WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ OIERJGOIERPIUPJ PERWP FERPNG
                    EWRNJG JNWER G[JWERGN WERNGW ENR[O NWERO[ NW[GNE
                    IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI WNRVO[WRTG
                    WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE VMWOTJVN
                    OWMV lORE RWEFO JWOFN WEONFO WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ
                    OIERJGOIERPIUPJ PERWP FERPNG EWRNJG JNWER G[JWERGN WERNGW
                    ENR[O NWERO[ NW[GNE IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI
                    WNRVO[WRTG WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE
                    VMWOTJVN OWMV lORE RWEFO JWOFN WEONFO
                    WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ OIERJGOIERPIUPJ PERWP FERPNG
                    EWRNJG JNWER G[JWERGN WERNGW ENR[O NWERO[ NW[GNE
                    IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI WNRVO[WRTG
                    WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE VMWOTJVN
                    OWMV lORE RWEFO JWOFN WEONFO WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ
                    OIERJGOIERPIUPJ PERWP FERPNG EWRNJG JNWER G[JWERGN WERNGW
                    ENR[O NWERO[ NW[GNE IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI
                    WNRVO[WRTG WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE
                    VMWOTJVN OWMV lORE RWEFO JWOFN WEONFO
                    WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ OIERJGOIERPIUPJ PERWP FERPNG
                    EWRNJG JNWER G[JWERGN WERNGW ENR[O NWERO[ NW[GNE
                    IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI WNRVO[WRTG
                    WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE VMWOTJVN
                    OWMV lORE RWEFO JWOFN WEONFO WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ
                    OIERJGOIERPIUPJ PERWP FERPNG EWRNJG JNWER G[JWERGN WERNGW
                    ENR[O NWERO[ NW[GNE IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI
                    WNRVO[WRTG WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE
                    VMWOTJVN OWMV lORE RWEFO JWOFN WEONFO
                    WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ OIERJGOIERPIUPJ PERWP FERPNG
                    EWRNJG JNWER G[JWERGN WERNGW ENR[O NWERO[ NW[GNE
                    IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI WNRVO[WRTG
                    WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE VMWOTJVN
                    OWMV lORE RWEFO JWOFN WEONFO WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ
                    OIERJGOIERPIUPJ PERWP FERPNG EWRNJG JNWER G[JWERGN WERNGW
                    ENR[O NWERO[ NW[GNE IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI
                    WNRVO[WRTG WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE
                    VMWOTJVN OWMV lORE RWEFO JWOFN WEONFO
                    WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ OIERJGOIERPIUPJ PERWP FERPNG
                    EWRNJG JNWER G[JWERGN WERNGW ENR[O NWERO[ NW[GNE
                    IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI WNRVO[WRTG
                    WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE VMWOTJVN
                    OWMV lORE RWEFO JWOFN WEONFO WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ
                    OIERJGOIERPIUPJ PERWP FERPNG EWRNJG JNWER G[JWERGN WERNGW
                    ENR[O NWERO[ NW[GNE IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI
                    WNRVO[WRTG WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE
                    VMWOTJVN OWMV lORE RWEFO JWOFN WEONFO
                    WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ OIERJGOIERPIUPJ PERWP FERPNG
                    EWRNJG JNWER G[JWERGN WERNGW ENR[O NWERO[ NW[GNE
                    IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI WNRVO[WRTG
                    WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE VMWOTJVN
                    OWMV lORE RWEFO JWOFN WEONFO WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ
                    OIERJGOIERPIUPJ PERWP FERPNG EWRNJG JNWER G[JWERGN WERNGW
                    ENR[O NWERO[ NW[GNE IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI
                    WNRVO[WRTG WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE
                    VMWOTJVN OWMV lORE RWEFO JWOFN WEONFO
                    WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ OIERJGOIERPIUPJ PERWP FERPNG
                    EWRNJG JNWER G[JWERGN WERNGW ENR[O NWERO[ NW[GNE
                    IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI WNRVO[WRTG
                    WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE VMWOTJVN
                    OWMV lORE RWEFO JWOFN WEONFO WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ
                    OIERJGOIERPIUPJ PERWP FERPNG EWRNJG JNWER G[JWERGN WERNGW
                    ENR[O NWERO[ NW[GNE IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI
                    WNRVO[WRTG WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE
                    VMWOTJVN OWMV lORE RWEFO JWOFN WEONFO
                    WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ OIERJGOIERPIUPJ PERWP FERPNG
                    EWRNJG JNWER G[JWERGN WERNGW ENR[O NWERO[ NW[GNE
                    IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI WNRVO[WRTG
                    WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE VMWOTJVN
                    OWMV lORE RWEFO JWOFN WEONFO WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ
                    OIERJGOIERPIUPJ PERWP FERPNG EWRNJG JNWER G[JWERGN WERNGW
                    ENR[O NWERO[ NW[GNE IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI
                    WNRVO[WRTG WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE
                    VMWOTJVN OWMV lORE RWEFO JWOFN WEONFO
                    WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ OIERJGOIERPIUPJ PERWP FERPNG
                    EWRNJG JNWER G[JWERGN WERNGW ENR[O NWERO[ NW[GNE
                    IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI WNRVO[WRTG
                    WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE VMWOTJVN
                    OWMV lORE RWEFO JWOFN WEONFO WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ
                    OIERJGOIERPIUPJ PERWP FERPNG EWRNJG JNWER G[JWERGN WERNGW
                    ENR[O NWERO[ NW[GNE IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI
                    WNRVO[WRTG WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE
                    VMWOTJVN OWMV lORE RWEFO JWOFN WEONFO
                    WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ OIERJGOIERPIUPJ PERWP FERPNG
                    EWRNJG JNWER G[JWERGN WERNGW ENR[O NWERO[ NW[GNE
                    IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI WNRVO[WRTG
                    WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE VMWOTJVN
                    OWMV lORE RWEFO JWOFN WEONFO WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ
                    OIERJGOIERPIUPJ PERWP FERPNG EWRNJG JNWER G[JWERGN WERNGW
                    ENR[O NWERO[ NW[GNE IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI
                    WNRVO[WRTG WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE
                    VMWOTJVN OWMV lORE RWEFO JWOFN WEONFO
                    WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ OIERJGOIERPIUPJ PERWP FERPNG
                    EWRNJG JNWER G[JWERGN WERNGW ENR[O NWERO[ NW[GNE
                    IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI WNRVO[WRTG
                    WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE VMWOTJVN
                    OWMV lORE RWEFO JWOFN WEONFO WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ
                    OIERJGOIERPIUPJ PERWP FERPNG EWRNJG JNWER G[JWERGN WERNGW
                    ENR[O NWERO[ NW[GNE IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI
                    WNRVO[WRTG WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE
                    VMWOTJVN OWMV lORE RWEFO JWOFN WEONFO
                    WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ OIERJGOIERPIUPJ PERWP FERPNG
                    EWRNJG JNWER G[JWERGN WERNGW ENR[O NWERO[ NW[GNE
                    IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI WNRVO[WRTG
                    WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE VMWOTJVN
                    OWMV lORE RWEFO JWOFN WEONFO WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ
                    OIERJGOIERPIUPJ PERWP FERPNG EWRNJG JNWER G[JWERGN WERNGW
                    ENR[O NWERO[ NW[GNE IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI
                    WNRVO[WRTG WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE
                    VMWOTJVN OWMV lORE RWEFO JWOFN WEONFO
                    WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ OIERJGOIERPIUPJ PERWP FERPNG
                    EWRNJG JNWER G[JWERGN WERNGW ENR[O NWERO[ NW[GNE
                    IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI WNRVO[WRTG
                    WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE VMWOTJVN
                    OWMV lORE RWEFO JWOFN WEONFO WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ
                    OIERJGOIERPIUPJ PERWP FERPNG EWRNJG JNWER G[JWERGN WERNGW
                    ENR[O NWERO[ NW[GNE IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI
                    WNRVO[WRTG WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE
                    VMWOTJVN OWMV lORE RWEFO JWOFN WEONFO
                    WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ OIERJGOIERPIUPJ PERWP FERPNG
                    EWRNJG JNWER G[JWERGN WERNGW ENR[O NWERO[ NW[GNE
                    IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI WNRVO[WRTG
                    WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE VMWOTJVN
                    OWMV lORE RWEFO JWOFN WEONFO WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ
                    OIERJGOIERPIUPJ PERWP FERPNG EWRNJG JNWER G[JWERGN WERNGW
                    ENR[O NWERO[ NW[GNE IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI
                    WNRVO[WRTG WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE
                    VMWOTJVN OWMV lORE RWEFO JWOFN WEONFO
                    WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ OIERJGOIERPIUPJ PERWP FERPNG
                    EWRNJG JNWER G[JWERGN WERNGW ENR[O NWERO[ NW[GNE
                    IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI WNRVO[WRTG
                    WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE VMWOTJVN
                    OWMV lORE RWEFO JWOFN WEONFO WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ
                    OIERJGOIERPIUPJ PERWP FERPNG EWRNJG JNWER G[JWERGN WERNGW
                    ENR[O NWERO[ NW[GNE IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI
                    WNRVO[WRTG WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE
                    VMWOTJVN OWMV lORE RWEFO JWOFN WEONFO
                    WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ OIERJGOIERPIUPJ PERWP FERPNG
                    EWRNJG JNWER G[JWERGN WERNGW ENR[O NWERO[ NW[GNE
                    IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI WNRVO[WRTG
                    WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE VMWOTJVN
                    OWMV lORE RWEFO JWOFN WEONFO WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ
                    OIERJGOIERPIUPJ PERWP FERPNG EWRNJG JNWER G[JWERGN WERNGW
                    ENR[O NWERO[ NW[GNE IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI
                    WNRVO[WRTG WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE
                    VMWOTJVN OWMV lORE RWEFO JWOFN WEONFO
                    WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ OIERJGOIERPIUPJ PERWP FERPNG
                    EWRNJG JNWER G[JWERGN WERNGW ENR[O NWERO[ NW[GNE
                    IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI WNRVO[WRTG
                    WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE VMWOTJVN
                    OWMV lORE RWEFO JWOFN WEONFO WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ
                    OIERJGOIERPIUPJ PERWP FERPNG EWRNJG JNWER G[JWERGN WERNGW
                    ENR[O NWERO[ NW[GNE IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI
                    WNRVO[WRTG WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE
                    VMWOTJVN OWMV lORE RWEFO JWOFN WEONFO
                    WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ OIERJGOIERPIUPJ PERWP FERPNG
                    EWRNJG JNWER G[JWERGN WERNGW ENR[O NWERO[ NW[GNE
                    IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI WNRVO[WRTG
                    WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE VMWOTJVN
                    OWMV lORE RWEFO JWOFN WEONFO WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ
                    OIERJGOIERPIUPJ PERWP FERPNG EWRNJG JNWER G[JWERGN WERNGW
                    ENR[O NWERO[ NW[GNE IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI
                    WNRVO[WRTG WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE
                    VMWOTJVN OWMV lORE RWEFO JWOFN WEONFO
                    WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ OIERJGOIERPIUPJ PERWP FERPNG
                    EWRNJG JNWER G[JWERGN WERNGW ENR[O NWERO[ NW[GNE
                    IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI WNRVO[WRTG
                    WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE VMWOTJVN
                    OWMV lORE RWEFO JWOFN WEONFO WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ
                    OIERJGOIERPIUPJ PERWP FERPNG EWRNJG JNWER G[JWERGN WERNGW
                    ENR[O NWERO[ NW[GNE IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI
                    WNRVO[WRTG WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE
                    VMWOTJVN OWMV lORE RWEFO JWOFN WEONFO
                    WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ OIERJGOIERPIUPJ PERWP FERPNG
                    EWRNJG JNWER G[JWERGN WERNGW ENR[O NWERO[ NW[GNE
                    IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI WNRVO[WRTG
                    WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE VMWOTJVN
                    OWMV lORE RWEFO JWOFN WEONFO WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ
                    OIERJGOIERPIUPJ PERWP FERPNG EWRNJG JNWER G[JWERGN WERNGW
                    ENR[O NWERO[ NW[GNE IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI
                    WNRVO[WRTG WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE
                    VMWOTJVN OWMV lORE RWEFO JWOFN WEONFO
                    WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ OIERJGOIERPIUPJ PERWP FERPNG
                    EWRNJG JNWER G[JWERGN WERNGW ENR[O NWERO[ NW[GNE
                    IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI WNRVO[WRTG
                    WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE VMWOTJVN
                    OWMV lORE RWEFO JWOFN WEONFO WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ
                    OIERJGOIERPIUPJ PERWP FERPNG EWRNJG JNWER G[JWERGN WERNGW
                    ENR[O NWERO[ NW[GNE IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI
                    WNRVO[WRTG WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE
                    VMWOTJVN OWMV lORE RWEFO JWOFN WEONFO
                    WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ OIERJGOIERPIUPJ PERWP FERPNG
                    EWRNJG JNWER G[JWERGN WERNGW ENR[O NWERO[ NW[GNE
                    IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI WNRVO[WRTG
                    WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE VMWOTJVN
                    OWMV lORE RWEFO JWOFN WEONFO WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ
                    OIERJGOIERPIUPJ PERWP FERPNG EWRNJG JNWER G[JWERGN WERNGW
                    ENR[O NWERO[ NW[GNE IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI
                    WNRVO[WRTG WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE
                    VMWOTJVN OWMV lORE RWEFO JWOFN WEONFO
                    WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ OIERJGOIERPIUPJ PERWP FERPNG
                    EWRNJG JNWER G[JWERGN WERNGW ENR[O NWERO[ NW[GNE
                    IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI WNRVO[WRTG
                    WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE VMWOTJVN
                    OWMV lORE RWEFO JWOFN WEONFO WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ
                    OIERJGOIERPIUPJ PERWP FERPNG EWRNJG JNWER G[JWERGN WERNGW
                    ENR[O NWERO[ NW[GNE IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI
                    WNRVO[WRTG WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE
                    VMWOTJVN OWMV lORE RWEFO JWOFN WEONFO
                    WEJNOFJO3OTRNMEWOIRJTOIWEJR OIJ OIERJGOIERPIUPJ PERWP FERPNG
                    EWRNJG JNWER G[JWERGN WERNGW ENR[O NWERO[ NW[GNE
                    IORVNOIWENVO[IEJKWRGJVWOEN[VON WO[INBVOI WNRVO[WRTG
                    WTGNBVPWJTRB[WOJTBOWBN NWT ONBOWPNTBO[WJNMTVOMWOE VMWOTJVN
                    OWMV{" "}
                </main>
                <Footer />
            </div>
        </div>
    );
};
