export const SET_USER_TOKENS = "SET_USER_TOKENS";
export const SET_ERROR_OF_LOGGED_AUTH = "SET_ERROR_OF_LOGGED_AUTH";

export const GET_CARS_LIST = " GET_CARS_LIST";
export const GET_CITY_LIST = "GET_CITY_LIST";
export const GET_ORDER_STATUS_LIST = "GET_ORDER_TATUS_LIST";

export const SET_PERIOD_TO_ORDER_LIST = "SET_PERIOD_TO_ORDER_LIST";
export const SET_CAR_TO_ORDER_LIST = "SET_CAR_TO_ORDER_LIST";
export const SET_CITY_TO_ORDER_LIST = "SET_CITY_TO_ORDER_LIST";
export const SET_ORDER_STATUS_TO_ORDER_LIST = "SET_ORDER_STATUS_TO_ORDER_LIST";
export const CHANGE_PAGE_ORDER_LIST = "CHANGE_PAGE_ORDER_LIST";
export const COUNT_OF_PAGES_OF_ORDER_LIST = "COUNT_OF_PAGES_OF_ORDER_LIST";
export const GET_FILTERED_ORDER_LIST = "GET_FILTERED_ORDER_LIST";
export const RESET_SETTINGS_ORDER_LIST = "RESET_SETTINGS_ORDER_LIST";
