export const SET_USER_TOKENS = "SET_USER_TOKENS";
export const SET_ERROR_OF_LOGGED_AUTH = "SET_ERROR_OF_LOGGED_AUTH";

export const GET_CARS_LIST = " GET_CARS_LIST";
export const GET_CITY_LIST = "GET_CITY_LIST";
export const GET_ORDER_STATUS_LIST = "GET_ORDER_TATUS_LIST";
export const GET_CATEGORY_LIST = "GET_CATEGORY_LIST";
export const SET_COLOR_LIST = "SET_COLOR_LIST";

export const SET_PERIOD_TO_ORDER_LIST = "SET_PERIOD_TO_ORDER_LIST";
export const SET_CAR_TO_ORDER_LIST = "SET_CAR_TO_ORDER_LIST";
export const SET_CITY_TO_ORDER_LIST = "SET_CITY_TO_ORDER_LIST";
export const SET_ORDER_STATUS_TO_ORDER_LIST = "SET_ORDER_STATUS_TO_ORDER_LIST";
export const CHANGE_PAGE_ORDER_LIST = "CHANGE_PAGE_ORDER_LIST";
export const COUNT_OF_PAGES_OF_ORDER_LIST = "COUNT_OF_PAGES_OF_ORDER_LIST";
export const GET_FILTERED_ORDER_LIST = "GET_FILTERED_ORDER_LIST";
export const RESET_SETTINGS_ORDER_LIST = "RESET_SETTINGS_ORDER_LIST";

export const SET_CARMODEL_TO_CARS_TABLE = "SET_CARMODEL_TO_CARS_TABLE";
export const SET_CATEGORY_TO_CARS_TABLE = "SET_CATEGORY_TO_CARS_TABLE";
export const SET_COLOR_TO_CARS_TABLE = "SET_COLOR_TO_CARS_TABLE";
export const SET_MIN_PRICE_TO_CARS_TABLE = "SET_MIN_PRICE_TO_CARS_TABLE";
export const SET_MAX_PRICE_TO_CARS_TABLE = "SET_MAX_PRICE_TO_CARS_TABLE";
export const CHANGE_PAGE_CARS_TABLE = "CHANGE_PAGE_CARS_TABLE";
export const COUNT_OF_PAGES_OF_CARS_TABLE = "COUNT_OF_PAGES_OF_CARS_TABLE";
export const GET_FILTERED_CARS_TABLE = "GET_FILTERED_CARS_TABLE";
export const RESET_SETTINGS_CARS_TABLE = "RESET_SETTINGS_CARS_TABLE";
