export const AUTH = "AUTH";
export const SET_USER_INFO = "SET_USER_INFO";

export const GET_MODEL_LIST = "GET_MODEL_LIST";
export const GET_CITY_LIST = "GET_CITY_LIST";
export const GET_STATUS_LIST = "GET_STATUS_LIST";
export const SET_PERIOD = "SET_PERIOD";
export const SET_SELECTED_MODEL = "SET_SELECTED_MODEL";
export const SET_SELECTED_CITY = "SET_SELECTED_CITY";
export const SET_SELECTED_STATUS = "SET_SELECTED_STATUS";
export const GET_ORDER_LIST = "GET_ORDER_LIST";
export const CHANGE_PAGE_ORDER_LIST = "CHANGE_PAGE_ORDER_LIST";
export const COUNT_OF_PAGES_OF_ORDER_LIST = " COUNT_OF_PAGES_OF_ORDER_LIST";
export const SET_ERROR = "SET_ERROR";
export const RESET_SETTINGS_ORDER_LIST = "RESET_SETTINGS_ORDER_LIST";
